### ISSUE TITLE
XSS Vulnerabilities Protection

### ISSUE THREAD

**Issue by prathamesh-mutkure** [AnyRoad/react-json-view-lite#10]
I want to use this library for rendering JSON data for a very big open-source project but they have concerns over security measures, specifically the XSS vulnerability protection.

Does this library provide out-of-the-box support or I'll have to manually do the thing?

**Comment by AnyRoad** [comment]
Hi,

This library does not use `dangerouslySetInnerHTML` (all data is rendered as String) or sets any HTML attributes like a.href so it should be XSS protected.
