### ISSUE TITLE
expanded class

### ISSUE THREAD

**Issue by dannybloe** [AnyRoad/react-json-view-lite#11]
Howdee,

Would it be possible to set a class when a section is collapsed or expanded? I don't like the arrow symbol used (twisty) so I disabled it in css and want to use :after to inject my own but there is no way to know if a node is collapsed or expanded so I cannot differentiate.

I also strongly suggest to not use a hard-coded html element for the twisty but solve it completely in css. That way you have full control over the styling of the json tree. And if that is not what you want then you could support perhaps two attributes for the component in which you can provide a (jsx/react) component that renders each twisty.

Cheers, 
Danny

**Comment by AnyRoad** [comment]
Hi,

Yes, good idea! I will replace arrows and `...` for collapsed content with css styles.
I'm planning to release new version next week, since I will make some breaking changes in the component properties I will release it as a new major version.

Thanks!

**Comment by AnyRoad** [comment]
Hi,

Just released the 1.0.0 version, please refer to the [migration guide](https://github.com/AnyRoad/react-json-view-lite#migration-from-the-09x-versions).

Thanks,
Andy.
