### ISSUE TITLE
Typo in the readme?

### ISSUE THREAD

**Issue by yurishkuro** [AnyRoad/react-json-view-lite#12]
<img width="953" alt="image" src="https://github.com/AnyRoad/react-json-view-lite/assets/3523016/b7a4e874-6b8b-449f-afbf-5bf2aee89069">

**Comment by John-Paul-R** [comment]
appears resolved

![image](https://github.com/AnyRoad/react-json-view-lite/assets/29154459/9db34750-79e8-4197-82f6-bd57b97c20a1)

**Comment by AnyRoad** [comment]
Sorry for the late reply, it happened to me as well last week... Seems like it is not a typo but misuse of the badge api or some problem on the bundlephobia.com side. I will try to investigate more once I have time.
