### ISSUE TITLE
don't add quotes to string

### ISSUE THREAD

**Issue by turbocrime** [AnyRoad/react-json-view-lite#22]
or at least provide the option to turn it off. this could be done with css, if necessary.

https://github.com/AnyRoad/react-json-view-lite/blob/cb6558c1cd04bd40d4bbf66591d3ef71a403c208/src/DataRenderer.tsx#L185

going further, punctuation could also be styled.

**Comment by AnyRoad** [comment]
Hi! Unfortunatelly styling is not very convinient, I will try to improve it in the next major version.

For now I've added the `noQuotesForStringValues` property to the [StyleProps](https://github.com/AnyRoad/react-json-view-lite?tab=readme-ov-file#styleprops). You can upgrade to the 1.3.0 version.

I've also added it to the storybook - https://anyroad.github.io/react-json-view-lite/?path=/story/json-view--render-strings-without-objects
