### ISSUE TITLE
pressing the spacebar expands/collapses and "pages down" in the browser

### ISSUE THREAD

**Issue by gregsadetsky** [AnyRoad/react-json-view-lite#24]
thanks for the great library!

I encountered a small issue -- when pressing the spacebar, [this code](https://github.com/AnyRoad/react-json-view-lite/blob/release/src/DataRenderer.tsx#L75) will expand/collapse nodes - which is a great behavior

however, since the event is not cancelled at that point, it bubbles further up and the browser will also "page down", which is not super great :-)

see video below.

[contributed fix here](https://github.com/AnyRoad/react-json-view-lite/pull/25).

![uF9RE9o9HDs-z-0-y-662bbde36ce4224c4e180cae](https://github.com/AnyRoad/react-json-view-lite/assets/1017304/443fc8e6-5cd4-454d-897c-dc787e14e8df)

**Comment by AnyRoad** [comment]
Thank you! Merged your PR and released v1.3.1.
