### ISSUE TITLE
suggestion: expandable labels should be clickable

### ISSUE THREAD

**Issue by gregsadetsky** [AnyRoad/react-json-view-lite#26]
me again :-)

a small thing that I noticed is that expanding nodes can be done by clicking the arrow, or the collapsed `{ ... }` block, but it's not possible to expand a node by clicking the key name. see video below.

![OAbWOmFP1DU-z-0-y-662bc07aa4d95544a99236a8](https://github.com/AnyRoad/react-json-view-lite/assets/1017304/e1350cf2-5668-4c6e-9a17-6c502a7cf86c)

I made a small change locally to [this line](https://github.com/AnyRoad/react-json-view-lite/blob/release/src/DataRenderer.tsx#L92) so that instead of

`{field && <span className={style.label} >{field}:</span>}`

it reads

`{field && <span className={style.label} onClick={toggleExpanded}>{field}:</span>}`

and that does exactly what I'm looking for:

![4r87iPD5VP8-z-0-y-662bc12efd6a3c0628a0f4bc](https://github.com/AnyRoad/react-json-view-lite/assets/1017304/bfae5ca3-7751-4ebb-9545-2216c9990616)

there are some small styling issues with this though:
- the `<span>` doesn't have `cursor: pointer`, which would be useful to make it clear that the node can be clicked
- a much smaller issue is that when clicking fast-ish on the node to expand/collapse it, you may end up selecting some of the text by mistake. that can be fixed by setting `user-select: none` -- this is probably optional (and would also introduce a weird inconsistency in that some nodes' text would not be selectable, while others would be)

---

I'd be happy to contribute a fix -- would you prefer a new style to be created, something like `expandableLabel`, and that (based on `label`) would have the `cursor:pointer` declaration..?

thank you!

**Comment by AnyRoad** [comment]
Hi! Thank you for the fix and suggestion!

I think some users may stil want to just select the field name with double click (for instance to copy it).
So it would be good to support both use cases with `expandableLabel` style and fallback to the `label` when first is not set. And make expanding by click on the field name optional as well.

**Comment by gregsadetsky** [comment]
hey, I just took a stab at implementing this in #27 -- feel free to leave comments here or in the PR. I took liberty with the naming (`clickToExpandNode` for the optional prop and `clickableLabel` for the style class) -- but obviously let me know what makes sense

I also added tests and was glad to keep the test coverage at 100% :-) cheers!

**Comment by AnyRoad** [comment]
Thanks! just merged and released version 1.4.0 👍

**Comment by gregsadetsky** [comment]
thank you!!
