### ISSUE TITLE
data重新赋值,key变更会报错

### ISSUE THREAD

**Issue by jia19920819** [AnyRoad/react-json-view-lite#36]
data重新赋值,json中key有变更会报错
react-dom.development.js:86 Warning: Internal React error: Expected static flag was missing. Please notify the React team.

**Comment by AnyRoad** [comment]
Can you please provide more information about the React version and library verison you use as well as the "data" value you assigned?

**Comment by jia19920819** [comment]
react:~18.3.1
react-json-view-lite:^2.0.1

import { JsonView, allExpanded, collapseAllNested, darkStyles, defaultStyles } from 'react-json-view-lite';
import 'react-json-view-lite/dist/index.css';
<JsonView data={data} style={defaultStyles} />

data 在其他操作下更新值就会报
data={"key", 1}  改为 data={"key": 2,"value": "yang"}

**Comment by AnyRoad** [comment]
经过查找，发现这种错误是由于hook使用不当造成的。在创建上面使用 JsonView 的钩子之前是否有 return 语句？

或者您能否提供更大的代码示例，因为可能还存在其他问题？

**Comment by jia19920819** [comment]
非常感谢你的回复，我单独做了一个简单的测试案例没有报这个错误，应该是我项目写的有bug，谢谢。
