### ISSUE TITLE
Please add the demo link for better documentation

### ISSUE THREAD

**Issue by idindrakusuma** [AnyRoad/react-json-view-lite#4]
Hi @AnyRoad 
Thank you for creating this package. For better in the README section, I think you need to add the demo link for this package.

For example, I've created the demo and how to use it in Codesanbox. 
https://codesandbox.io/s/react-json-view-lite-example-wvdjl

Thanks!

**Comment by AnyRoad** [comment]
Hi @idindrakusuma  , sorry for the late reply, I've added the link 😃 
Thanks you for your interest in the project!
