### ISSUE TITLE
Remove dependency on react version

### ISSUE THREAD

**Issue by essuraj** [AnyRoad/react-json-view-lite#5]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: ****_next@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.13.1 || ^17.0.0" from react-json-view-lite@0.9.4
npm ERR! node_modules/react-json-view-lite
npm ERR!   react-json-view-lite@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by AnyRoad** [comment]
Hi,

I've just published version 0.9.5 which has all 16,17,18 versions in peer dependencies.

Thanks!
