### ISSUE TITLE
Show empty keys in objects

### ISSUE THREAD

**Issue by dartess** [AnyRoad/react-json-view-lite#9]
<img width="221" alt="image" src="https://github.com/AnyRoad/react-json-view-lite/assets/15047511/21f1dd8b-5f6b-4b3b-95e7-3ca031ee0f92">

At first I did not understand what "-1" means in an object. It's actually `"": -1`. Maybe it's worth showing such keys in this way? Or will it require a lot of modifications?

**Comment by AnyRoad** [comment]
While empty string key is not so common I think it is a bug and I will fix it in the next version.

**Comment by AnyRoad** [comment]
Fixed in the version 0.9.8, storybook updated with the example: https://anyroad.github.io/react-json-view-lite/?path=/story/json-view--basic
